import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'appName': 'Delivery App',
      'home': 'Home',
      'orders': 'Orders',
      'profile': 'Profile',
      'tasks': 'Tasks',
      'history': 'History',
      'dashboard': 'Dashboard',
      'users': 'Users',
      'login': 'Login',
      'register': 'Register',
      'email': 'Email',
      'password': 'Password',
      'name': 'Name',
      'role': 'Role',
      'signIn': 'Sign In',
      'signUp': 'Sign Up',
      'signOut': 'Sign Out',
      'save': 'Save',
      'cancel': 'Cancel',
      'dismiss': 'Dismiss',
      'ok': 'OK',
      'search': 'Search',
      'noResults': 'No results',
      'loading': 'Loading...',
      'error': 'Error',
      'retry': 'Try Again',
      'pending': 'Pending',
      'accepted': 'Accepted',
      'inProgress': 'In Progress',
      'completed': 'Completed',
      'cancelled': 'Cancelled',
      'maintenance': 'Maintenance',
      'delivery': 'Delivery',
      'createNewOrder': 'Create New Order',
      'active': 'Active',
      'recentOrders': 'Recent Orders',
      'noOrdersYet': 'No orders yet. Create your first order!',
      'noActiveTasks': 'No active tasks',
      'newTasksWillAppear': 'New tasks will appear here when assigned',
      'myTasks': 'My Tasks',
      'chat': 'Chat',
      'chats': 'Chats',
      'typeMessage': 'Type a message...',
      'send': 'Send',
      'reviews': 'Reviews',
      'rating': 'Rating',
      'comment': 'Comment',
      'submit': 'Submit',
      'rateTechnician': 'Rate Technician',
      'trackOrder': 'Track Order',
      'orderDetail': 'Order Detail',
      'title': 'Title',
      'description': 'Description',
      'category': 'Category',
      'type': 'Type',
      'address': 'Address',
      'date': 'Date',
      'status': 'Status',
      'customer': 'Customer',
      'technician': 'Technician',
      'admin': 'Admin',
      'logout': 'Logout',
      'language': 'Language',
      'theme': 'Theme',
      'english': 'English',
      'arabic': 'Arabic',
      'noConnection': 'No Connection',
      'somethingWentWrong': 'Something Went Wrong',
      'authenticationError': 'Authentication Error',
      'accessDenied': 'Access Denied',
      'notFound': 'Not Found',
      'invalidInput': 'Invalid Input',
      'failedToLoadOrders': 'Failed to load orders',
      'orderCreated': 'Order created successfully!',
      'orderUpdated': 'Order updated successfully!',
      'quickActions': 'Quick Actions',
      'totalOrders': 'Total Orders',
      'activeOrders': 'Active Orders',
      'completedOrders': 'Completed Orders',
      'welcomeBack': 'Welcome Back',
      'signInToContinue': 'Sign in to continue',
      'createAccount': 'Create Account',
      'signUpToGetStarted': 'Sign up to get started',
      'fullName': 'Full Name',
      'confirmPassword': 'Confirm Password',
      'iAmA': 'I am a',
      'enterYourEmail': 'Enter your email',
      'enterYourPassword': 'Enter your password',
      'enterYourName': 'Enter your name',
      'confirmYourPassword': 'Confirm your password',
      'emailRequired': 'Email is required',
      'passwordRequired': 'Password is required',
      'nameRequired': 'Name is required',
      'passwordMinLength': 'Password must be at least 6 characters',
      'passwordsDoNotMatch': 'Passwords do not match',
      'dontHaveAccount': "Don't have an account? Sign Up",
      'alreadyHaveAccount': 'Already have an account? Sign In',
      'myOrders': 'My Orders',
      'createOrder': 'Create Order',
      'orderType': 'Order Type',
      'briefTitle': 'Brief title for the order',
      'titleRequired': 'Title is required',
      'describeOrder': 'Describe the issue or delivery details',
      'descriptionRequired': 'Description is required',
      'fullAddress': 'Full address',
      'addressRequired': 'Address is required',
      'submitOrder': 'Submit Order',
      'created': 'Created',
      'photos': 'Photos',
      'actions': 'Actions',
      'chatWithTechnician': 'Chat with Technician',
      'cancelOrder': 'Cancel Order',
      'assigned': 'Assigned',
      'start': 'Start',
      'complete': 'Complete',
      'orderNotFound': 'Order not found',
      'taskNotFound': 'Task not found',
      'noCompletedTasks': 'No completed tasks',
      'allOrders': 'All Orders',
      'all': 'All',
      'noOrdersFound': 'No orders found',
      'noUsersFound': 'No users found',
      'customerPrefix': 'Customer:',
      'technicianPrefix': 'Technician:',
      'overview': 'Overview',
      'customers': 'Customers',
      'technicians': 'Technicians',
      'communicate': 'Communicate',
      'chatWithCustomer': 'Chat with Customer',
      'markInProgress': 'Mark In Progress',
      'markCompleted': 'Mark Completed',
      'statusUpdatedTo': 'Status updated to',
      'technicianAssigned': 'Technician assigned',
      'viewChat': 'View Chat',
      'management': 'Management',
      'assignTechnician': 'Assign Technician',
      'updateStatus': 'Update Status',
      'noConversationsYet': 'No conversations yet',
      'chatWithTechnicianAboutOrder': 'Chat with your technician about an order',
      'noMessagesYetSayHello': 'No messages yet. Say hello!',
      'orderDetails': 'Order Details',
      'deliveryAddress': 'Delivery Address',
      'orderCancelled': 'Order Cancelled',
      'pleaseSelectRating': 'Please select a rating',
      'reviewSubmitted': 'Review submitted!',
      'howWasYourExperience': 'How was your experience?',
      'rateTechnicianDescription': 'Rate the technician who worked on your order',
      'terrible': 'Terrible',
      'poor': 'Poor',
      'okay': 'Okay',
      'good': 'Good',
      'excellent': 'Excellent',
      'commentOptional': 'Comment (optional)',
      'tellUsAboutExperience': 'Tell us about your experience...',
      'submitReview': 'Submit Review',
      'deleteAccount': 'Delete Account',
      'deleteConfirmation': 'This action cannot be undone. Your account and data will be permanently deleted.',
      'delete': 'Delete',
      'dark': 'Dark',
      'light': 'Light',
      'plumbing': 'Plumbing',
      'electrical': 'Electrical',
      'carpentry': 'Carpentry',
      'cleaning': 'Cleaning',
      'painting': 'Painting',
      'hvac': 'HVAC',
      'applianceRepair': 'Appliance Repair',
      'general': 'General',
      'parcel': 'Parcel',
      'food': 'Food',
      'groceries': 'Groceries',
    },
    'ar': {
      'appName': 'تطبيق التوصيل',
      'home': 'الرئيسية',
      'orders': 'الطلبات',
      'profile': 'الملف الشخصي',
      'tasks': 'المهام',
      'history': 'السجل',
      'dashboard': 'لوحة التحكم',
      'users': 'المستخدمين',
      'login': 'تسجيل الدخول',
      'register': 'إنشاء حساب',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'name': 'الاسم',
      'role': 'الدور',
      'signIn': 'تسجيل الدخول',
      'signUp': 'إنشاء حساب',
      'signOut': 'تسجيل الخروج',
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'dismiss': 'تجاهل',
      'ok': 'موافق',
      'search': 'بحث',
      'noResults': 'لا توجد نتائج',
      'loading': 'جارٍ التحميل...',
      'error': 'خطأ',
      'retry': 'إعادة المحاولة',
      'pending': 'قيد الانتظار',
      'accepted': 'مقبول',
      'inProgress': 'قيد التنفيذ',
      'completed': 'مكتمل',
      'cancelled': 'ملغي',
      'maintenance': 'صيانة',
      'delivery': 'توصيل',
      'createNewOrder': 'إنشاء طلب جديد',
      'active': 'نشط',
      'recentOrders': 'الطلبات الأخيرة',
      'noOrdersYet': 'لا توجد طلبات بعد. قم بإنشاء طلبك الأول!',
      'noActiveTasks': 'لا توجد مهام نشطة',
      'newTasksWillAppear': 'ستظهر المهام الجديدة هنا عند التعيين',
      'myTasks': 'مهامي',
      'chat': 'محادثة',
      'chats': 'المحادثات',
      'typeMessage': 'اكتب رسالة...',
      'send': 'إرسال',
      'reviews': 'التقييمات',
      'rating': 'التقييم',
      'comment': 'تعليق',
      'submit': 'إرسال',
      'rateTechnician': 'تقييم الفني',
      'trackOrder': 'تتبع الطلب',
      'orderDetail': 'تفاصيل الطلب',
      'title': 'العنوان',
      'description': 'الوصف',
      'category': 'التصنيف',
      'type': 'النوع',
      'address': 'العنوان',
      'date': 'التاريخ',
      'status': 'الحالة',
      'customer': 'عميل',
      'technician': 'فني',
      'admin': 'مدير',
      'logout': 'تسجيل الخروج',
      'language': 'اللغة',
      'theme': 'المظهر',
      'english': 'الإنجليزية',
      'arabic': 'العربية',
      'noConnection': 'لا يوجد اتصال',
      'somethingWentWrong': 'حدث خطأ ما',
      'authenticationError': 'خطأ في المصادقة',
      'accessDenied': 'تم رفض الوصول',
      'notFound': 'غير موجود',
      'invalidInput': 'إدخال غير صالح',
      'failedToLoadOrders': 'فشل تحميل الطلبات',
      'orderCreated': 'تم إنشاء الطلب بنجاح!',
      'orderUpdated': 'تم تحديث الطلب بنجاح!',
      'quickActions': 'إجراءات سريعة',
      'totalOrders': 'إجمالي الطلبات',
      'activeOrders': 'الطلبات النشطة',
      'completedOrders': 'الطلبات المكتملة',
      'welcomeBack': 'مرحباً بعودتك',
      'signInToContinue': 'سجل الدخول للمتابعة',
      'createAccount': 'إنشاء حساب',
      'signUpToGetStarted': 'سجل للبدء',
      'fullName': 'الاسم الكامل',
      'confirmPassword': 'تأكيد كلمة المرور',
      'iAmA': 'أنا',
      'enterYourEmail': 'أدخل بريدك الإلكتروني',
      'enterYourPassword': 'أدخل كلمة المرور',
      'enterYourName': 'أدخل اسمك',
      'confirmYourPassword': 'أكد كلمة المرور',
      'emailRequired': 'البريد الإلكتروني مطلوب',
      'passwordRequired': 'كلمة المرور مطلوبة',
      'nameRequired': 'الاسم مطلوب',
      'passwordMinLength': 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
      'passwordsDoNotMatch': 'كلمتا المرور غير متطابقتين',
      'dontHaveAccount': 'ليس لديك حساب؟ سجل الآن',
      'alreadyHaveAccount': 'لديك حساب بالفعل؟ تسجيل الدخول',
      'myOrders': 'طلباتي',
      'createOrder': 'إنشاء طلب',
      'orderType': 'نوع الطلب',
      'briefTitle': 'عنوان مختصر للطلب',
      'titleRequired': 'العنوان مطلوب',
      'describeOrder': 'صف المشكلة أو تفاصيل التوصيل',
      'descriptionRequired': 'الوصف مطلوب',
      'fullAddress': 'العنوان الكامل',
      'addressRequired': 'العنوان مطلوب',
      'submitOrder': 'إرسال الطلب',
      'created': 'تم الإنشاء',
      'photos': 'الصور',
      'actions': 'الإجراءات',
      'chatWithTechnician': 'محادثة مع الفني',
      'cancelOrder': 'إلغاء الطلب',
      'assigned': 'تم التعيين',
      'start': 'بدء',
      'complete': 'إكمال',
      'orderNotFound': 'الطلب غير موجود',
      'taskNotFound': 'المهمة غير موجودة',
      'noCompletedTasks': 'لا توجد مهام مكتملة',
      'allOrders': 'جميع الطلبات',
      'all': 'الكل',
      'noOrdersFound': 'لم يتم العثور على طلبات',
      'noUsersFound': 'لم يتم العثور على مستخدمين',
      'customerPrefix': 'العميل:',
      'technicianPrefix': 'الفني:',
      'overview': 'نظرة عامة',
      'customers': 'العملاء',
      'technicians': 'الفنيين',
      'communicate': 'تواصل',
      'chatWithCustomer': 'محادثة مع العميل',
      'markInProgress': 'تحديد قيد التنفيذ',
      'markCompleted': 'تحديد مكتمل',
      'statusUpdatedTo': 'تم تحديث الحالة إلى',
      'technicianAssigned': 'تم تعيين الفني',
      'viewChat': 'عرض المحادثة',
      'management': 'إدارة',
      'assignTechnician': 'تعيين فني',
      'updateStatus': 'تحديث الحالة',
      'noConversationsYet': 'لا توجد محادثات بعد',
      'chatWithTechnicianAboutOrder': 'تحدث مع فنييك حول طلب',
      'noMessagesYetSayHello': 'لا توجد رسائل بعد. قل مرحباً!',
      'orderDetails': 'تفاصيل الطلب',
      'deliveryAddress': 'عنوان التوصيل',
      'orderCancelled': 'تم إلغاء الطلب',
      'pleaseSelectRating': 'الرجاء اختيار تقييم',
      'reviewSubmitted': 'تم إرسال التقييم!',
      'howWasYourExperience': 'كيف كانت تجربتك؟',
      'rateTechnicianDescription': 'قم بتقييم الفني الذي عمل على طلبك',
      'terrible': 'سيء جداً',
      'poor': 'ضعيف',
      'okay': 'مقبول',
      'good': 'جيد',
      'excellent': 'ممتاز',
      'commentOptional': 'تعليق (اختياري)',
      'tellUsAboutExperience': 'أخبرنا عن تجربتك...',
      'submitReview': 'إرسال التقييم',
      'deleteAccount': 'حذف الحساب',
      'deleteConfirmation': 'لا يمكن التراجع عن هذا الإجراء. سيتم حذف حسابك وبياناتك بشكل دائم.',
      'delete': 'حذف',
      'dark': 'داكن',
      'light': 'فاتح',
      'plumbing': 'سباكة',
      'electrical': 'كهرباء',
      'carpentry': 'نجارة',
      'cleaning': 'تنظيف',
      'painting': 'دهان',
      'hvac': 'تكييف وتدفئة',
      'applianceRepair': 'إصلاح أجهزة',
      'general': 'عام',
      'parcel': 'طرود',
      'food': 'طعام',
      'groceries': 'بقالة',
    },
  };

  String translate(String key) {
    return _translations[locale.languageCode]?[key]
        ?? _translations['en']?[key]
        ?? key;
  }

  bool get isRtl => locale.languageCode == 'ar';
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) {
    return Future.value(AppLocalizations(locale));
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
